# Generated by Django 5.2.1 on 2026-01-30 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solar', '0003_employee_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
