# Generated by Django 5.2.1 on 2026-02-05 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Solar', '0004_alter_employee_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_approved',
        ),
    ]
