# Generated by Django 5.2.1 on 2026-02-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solar', '0005_remove_user_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarEstimation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('monthly_units', models.PositiveIntegerField(help_text='Monthly electricity consumption (units)')),
                ('building_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial')], max_length=20)),
                ('roof_type', models.CharField(choices=[('flat', 'Flat'), ('sloped', 'Sloped')], max_length=20)),
                ('roof_area', models.PositiveIntegerField(help_text='Roof area in sq.ft')),
                ('power_cut', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('backup_required', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
