# Generated by Django 5.2.1 on 2026-02-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solar', '0006_solarestimation_employee_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solarestimation',
            name='building_type',
            field=models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('factory', 'Factory'), ('warehouse', 'Warehouse'), ('hospital', 'Hospital'), ('school', 'School'), ('skyscraper', 'Skyscraper'), ('office', 'Office Building'), ('cultural', 'Cultural Centre'), ('industrial', 'Industrial Building'), ('carport', 'Residential Carports'), ('agricultural', 'Agricultural Building')], max_length=30),
        ),
        migrations.AlterField(
            model_name='solarestimation',
            name='power_cut',
            field=models.CharField(choices=[('none', 'None'), ('occasional', 'Occasional'), ('frequent', 'Frequent')], max_length=15),
        ),
    ]
