# Generated by Django 5.2.1 on 2026-02-13 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solar', '0007_alter_solarestimation_building_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarestimation',
            name='user',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='solar_estimations', to='Solar.user'),
            preserve_default=False,
        ),
    ]
