# Generated by Django 5.2.1 on 2026-02-13 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solar', '0008_solarestimation_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarTechnicalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_units', models.FloatField()),
                ('system_size', models.FloatField()),
                ('roof_required', models.IntegerField()),
                ('panels_needed', models.IntegerField()),
                ('sun_hours', models.FloatField(default=5)),
                ('loss_factor', models.FloatField(default=1.2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estimation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technical', to='Solar.solarestimation')),
            ],
        ),
    ]
