# Generated by Django 5.2.10 on 2026-03-07 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solar', '0012_passwordresetotp_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solartechnicaldata',
            name='system',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
