# Generated by Django 5.2.10 on 2026-03-07 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solar', '0013_solartechnicaldata_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarestimation',
            name='system',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
