# Generated by Django 5.2.10 on 2026-03-07 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Solar', '0014_solarestimation_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solarestimation',
            name='system',
        ),
    ]
