# Generated by Django 5.2.10 on 2026-03-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solar', '0015_remove_solarestimation_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarestimation',
            name='apply_subsidy',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AddField(
            model_name='solarestimation',
            name='lightning_protection',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AddField(
            model_name='solarestimation',
            name='subsidy_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='solarestimation',
            name='surge_protection',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AddField(
            model_name='solarestimation',
            name='system',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='solartechnicaldata',
            name='protection_cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='solartechnicaldata',
            name='subsidy_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='solartechnicaldata',
            name='subsidy_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='solartechnicaldata',
            name='total_final_cost',
            field=models.FloatField(default=0.0),
        ),
    ]
