# Generated by Django 5.2.10 on 2026-03-07 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Solar', '0016_solarestimation_apply_subsidy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresetotp',
            name='user',
        ),
    ]
