# Generated by Django 5.2.10 on 2026-03-07 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solar', '0017_remove_passwordresetotp_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetOTPUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Solar.user')),
            ],
        ),
    ]
