# Generated by Django 5.1.7 on 2026-03-13 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solar', '0018_passwordresetotpuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarInstallationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_source', models.CharField(choices=[('estimation', 'Based on my last estimation'), ('store', 'Bought from the Solar Store'), ('external', 'Already have my own equipment')], default='estimation', max_length=20)),
                ('system_size', models.FloatField(help_text='kW')),
                ('panels_count', models.PositiveIntegerField()),
                ('address', models.TextField()),
                ('preferred_date', models.DateField()),
                ('site_photos', models.ImageField(blank=True, null=True, upload_to='installation_sites/')),
                ('additional_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('investigation_scheduled', 'Site Investigation Scheduled'), ('investigation_completed', 'Site Investigation Completed'), ('approved', 'Approved for Installation'), ('rejected', 'Request Rejected')], default='pending', max_length=30)),
                ('investigation_date', models.DateField(blank=True, help_text='Set by Admin', null=True)),
                ('admin_feedback', models.TextField(blank=True, help_text='Reason for rejection or instructions for approval')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estimation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Solar.solarestimation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
