# Generated by Django 5.1.7 on 2026-03-13 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solar', '0019_solarinstallationrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solarinstallationrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Solar.user'),
        ),
    ]
