# Generated by Django 6.0 on 2026-04-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solar', '0020_alter_solarinstallationrequest_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('panel', 'Solar Panel'), ('inverter', 'Inverter'), ('mppt', 'MPPT Charger'), ('battery', 'Battery'), ('protection', 'Surge/Lighting Protector'), ('accessory', 'Cables & Accessories')], max_length=20)),
                ('brand', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('capacity_rating', models.CharField(blank=True, help_text='e.g. 450W or 100Ah', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
