# Generated by Django 6.0 on 2026-04-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solar', '0021_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model_number',
            field=models.CharField(blank=True, help_text='Specific model or version', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='voltage',
            field=models.CharField(blank=True, help_text='e.g. 12V, 24V, 48V', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='capacity_rating',
            field=models.CharField(blank=True, help_text='e.g. 450W, 5kW, 100Ah, 60A', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('panel', 'Solar Panel (Mono/Poly/Bifacial)'), ('inverter', 'Inverter (String/Micro/Hybrid)'), ('mppt', 'Charge Controller (MPPT/PWM)'), ('battery', 'Battery Storage (Lithium/Lead-Acid)'), ('protection', 'Protection (SPD/Arrestors/Breakers)'), ('structure', 'Mounting & Racking System'), ('accessory', 'Cables & Connectors (MC4/PV)'), ('monitoring', 'Monitoring & Smart Gateways')], max_length=20),
        ),
    ]
