# Generated by Django 6.0 on 2026-04-22 10:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solar', '0022_product_model_number_product_voltage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='model_number',
        ),
        migrations.AddField(
            model_name='product',
            name='sub_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='capacity_rating',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('panel', 'Solar Panel'), ('inverter', 'Inverter'), ('mppt', 'MPPT Charger'), ('battery', 'Battery'), ('protection', 'Surge/Lighting Protector'), ('structure', 'Mounting & Racking'), ('accessory', 'Cables & Accessories'), ('monitoring', 'Monitoring & Smart Gateways')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='voltage',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
