# Generated by Django 5.1.7 on 2026-04-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solar', '0023_remove_product_model_number_product_sub_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
