# Generated by Django 5.1.7 on 2026-04-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solar', '0024_product_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='solarinstallationrequest',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
