# Generated by Django 5.1.7 on 2026-04-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solar', '0025_remove_product_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solarinstallationrequest',
            name='investigation_date',
        ),
        migrations.AlterField(
            model_name='solarinstallationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('investigation_scheduled', 'Site Investigation Scheduled'), ('investigation_completed', 'Site Investigation Completed'), ('approved', 'Approved for Installation'), ('completed', 'Installation Completed'), ('rejected', 'Request Rejected')], default='pending', max_length=30),
        ),
    ]
