# Generated by Django 5.1.7 on 2026-04-25 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Solar', '0027_workassignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workassignment',
            options={'ordering': ['scheduled_date', '-assigned_at']},
        ),
        migrations.AlterUniqueTogether(
            name='workassignment',
            unique_together={('request', 'employee', 'work_type')},
        ),
    ]
