# Generated by Django 5.1.7 on 2026-04-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solar', '0028_alter_workassignment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workassignment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workassignment',
            name='employee_feedback',
            field=models.TextField(blank=True, help_text='Notes from employee after completion'),
        ),
    ]
