# Generated by Django 5.1.7 on 2026-05-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solar', '0029_workassignment_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='efficiency',
            field=models.CharField(blank=True, help_text='e.g. 21% for panels or 98% for inverters', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='technical_specs',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='utility_group',
            field=models.CharField(choices=[('infra', 'Installation Components (Panels, Inverters, etc.)'), ('appliance', 'Solar Appliances (Fans, Lights, Pumps)'), ('other', 'Other Products')], default='infra', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_years',
            field=models.PositiveIntegerField(default=1, help_text='Warranty period in years'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('panel', 'Solar Panel'), ('inverter', 'Inverter'), ('mppt', 'MPPT Charger'), ('battery', 'Battery'), ('protection', 'Surge/Lighting Protector'), ('structure', 'Mounting & Racking'), ('accessory', 'Cables & Accessories'), ('monitoring', 'Monitoring & Smart Gateways'), ('light', 'Solar Street/Garden Light'), ('fan', 'Solar DC Fan'), ('pump', 'Solar Water Pump'), ('heater', 'Solar Water Heater'), ('other', 'Miscellaneous Item')], max_length=20),
        ),
    ]
