# Generated by Django 5.1.7 on 2026-05-01 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Solar', '0030_product_efficiency_product_technical_specs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='capacity_rating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sub_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='voltage',
        ),
    ]
