# Generated by Django 5.1.7 on 2026-05-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solar', '0031_remove_product_capacity_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='country_of_origin',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='model_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
