# Generated by Django 5.1.7 on 2026-05-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solar', '0032_product_country_of_origin_product_model_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='highlights',
            field=models.TextField(blank=True, help_text='What makes this product stand out? (e.g., Best for high-temperature areas, sleek all-black design)'),
        ),
    ]
