# Generated by Django 5.1.7 on 2026-05-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solar', '0033_product_highlights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='warranty_years',
            field=models.PositiveIntegerField(default=0, help_text='Warranty period in years. Enter 0 for no warranty.'),
        ),
    ]
