# Generated by Django 5.1.7 on 2026-05-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solar', '0037_alter_cartitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=23, max_digits=10),
            preserve_default=False,
        ),
    ]
