# Generated by Django 5.1.7 on 2026-05-05 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solar', '0039_product_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallationPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success')], default='Pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Solar.solarinstallationrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Solar.user')),
            ],
        ),
    ]
