# Generated by Django 5.1.7 on 2026-05-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solar', '0040_installationpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarinstallationrequest',
            name='installation_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='solarinstallationrequest',
            name='admin_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='InstallationPayment',
        ),
    ]
