# Generated by Django 5.1.7 on 2026-05-05 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solar', '0041_solarinstallationrequest_installation_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallationPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('installation_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='installationpayment', to='Solar.solarinstallationrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Solar.user')),
            ],
        ),
    ]
