# Generated by Django 5.1.7 on 2026-05-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solar', '0042_installationpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarinstallationrequest',
            name='installation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
