# Generated by Django 5.1.7 on 2026-05-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solar', '0043_solarinstallationrequest_installation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='installationpayment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
