# Generated by Django 5.1.7 on 2026-05-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solar', '0044_installationpayment_paid_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='installationpayment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('upi', 'UPI'), ('card', 'Card'), ('netbanking', 'Net Banking')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='installationpayment',
            name='transaction_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
