# Generated by Django 5.1.7 on 2026-05-07 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solar', '0045_installationpayment_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
