# Generated by Django 5.1.7 on 2026-05-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solar', '0046_product_payment_paid_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_payment',
            name='payment_method',
            field=models.CharField(choices=[('upi', 'UPI'), ('card', 'Credit/Debit Card'), ('netbanking', 'Net Banking')], default='upi', max_length=20),
        ),
    ]
