# Generated by Django 5.1.7 on 2026-05-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solar', '0048_product_payment_shipping_address_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarestimation',
            name='subsidy_fixed_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='solarestimation',
            name='apply_subsidy',
            field=models.CharField(choices=[('no', 'No Subsidy'), ('percentage', 'Custom Percentage'), ('fixed_amount', 'Custom Fixed Amount')], default='no', max_length=20),
        ),
    ]
