# Generated by Django 5.1.7 on 2026-05-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solar', '0049_solarestimation_subsidy_fixed_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solartechnicaldata',
            name='base_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='solartechnicaldata',
            name='battery_cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='solartechnicaldata',
            name='installation_fee',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='solartechnicaldata',
            name='inverter_cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='solartechnicaldata',
            name='mppt_cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='solartechnicaldata',
            name='panel_cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='solartechnicaldata',
            name='panel_unit_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='solartechnicaldata',
            name='panel_wattage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='solartechnicaldata',
            name='structure_cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='solartechnicaldata',
            name='tax_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
