# Generated by Django 5.1.7 on 2026-05-23 14:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solar', '0050_solartechnicaldata_base_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workassignment',
            name='proof_file',
            field=models.FileField(blank=True, null=True, upload_to='work_proofs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'mp4', 'mkv', 'mov'])]),
        ),
        migrations.AddField(
            model_name='workassignment',
            name='report_text',
            field=models.TextField(blank=True, help_text='Detailed summary of the work done.'),
        ),
    ]
