# Generated by Django 5.1.7 on 2026-05-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solar', '0051_workassignment_proof_file_workassignment_report_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solarestimation',
            name='system',
        ),
        migrations.AddField(
            model_name='solartechnicaldata',
            name='is_finalized',
            field=models.BooleanField(default=False),
        ),
    ]
