# Generated by Django 5.1.7 on 2026-05-29 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solar', '0052_remove_solarestimation_system_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Solar.user'),
        ),
        migrations.DeleteModel(
            name='PasswordResetOTPUser',
        ),
    ]
