# Generated by Django 5.1.7 on 2026-06-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solar', '0053_passwordresetotp_user_delete_passwordresetotpuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='installationpayment',
            name='transaction_details',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='solarestimation',
            name='apply_subsidy',
            field=models.CharField(choices=[('no', 'No Subsidy'), ('percentage', 'Custom Percentage'), ('fixed_amount', 'Custom Fixed Amount')], default='no', max_length=15),
        ),
        migrations.AlterField(
            model_name='solarestimation',
            name='backup_required',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='solarestimation',
            name='roof_type',
            field=models.CharField(choices=[('flat', 'Flat'), ('sloped', 'Sloped')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='street_address',
            field=models.CharField(max_length=100),
        ),
    ]
