from django.urls import path
from Solar import views

urlpatterns = [
    path('',views.index,name='index'),
    path('user_register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
    path('employee_register/', views.employee_register, name='employee_register'),
    path('employee_login/', views.employee_login, name='employee_login'),
    path('user_home/', views.user_home, name='user_home'),
    path('employee_home/', views.employee_home, name='employee_home'),
    path('admin_login/', views.admin_login, name='admin_login'),
    path('admin_dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('user_profile/', views.user_profile, name='user_profile'),
    path('edit_user_profile/', views.edit_user_profile, name='edit_user_profile'),
    path('employee_profile/', views.employee_profile, name='employee_profile'),
    path('logout/', views.logout, name='logout'),
    path('edit_employee_profile/', views.edit_employee_profile, name='edit_employee_profile'),
    path('assign_work/', views.assign_work, name='assign_work'),
    path('submit_work_report/<int:assignment_id>/', views.submit_work_report, name='submit_work_report'),
    path('complete_assignment/<int:assignment_id>/', views.complete_assignment, name='complete_assignment'),
    path('delete_user_account/', views.delete_user_account, name='delete_user_account'),

    path('services/', views.services, name='services'),
    path('solar_estimation_form/', views.solar_estimation_form, name='solar_estimation_form'),
    path('solar_estimation_form/<int:estimation_id>/', views.solar_estimation_form, name='solar_estimation_edit'),
    path('solar_recommendation/<int:estimation_id>/', views.solar_recommendation, name='solar_recommendation'),
    path('solar-system-size/<int:estimation_id>/',views.solar_system_size,name='solar_system_size'),
    path('chatbot/', views.chatbot, name='chatbot'),
    path('chatbot_index/', views.chatbot_index, name='chatbot_index'),

    path('forgot-password/<str:user_type>/', views.forgot_password, name='forgot_password'),
    path('verify-otp/<str:user_type>/', views.verify_otp, name='verify_otp'),
    path('reset-password/<str:user_type>/', views.reset_password, name='reset_password'),


    path('solar/history/', views.solar_history, name='solar_history'),
    path('solar/delete/<int:estimation_id>/', views.delete_estimation, name='delete_estimation'),
    path('solar/quotation/<int:estimation_id>/', views.solar_quotation, name='solar_quotation'),
    path('solar/quotation/download/<int:estimation_id>/', views.download_quotation_pdf, name='download_quotation_pdf'),
    path('approve-employee/<int:emp_id>/', views.approve_employee, name='approve_employee'),
    path('installation_request/', views.installation_request_view, name='installation_request'),
    path('manage-request/<int:pk>/<str:status>/', views.manage_installation_request, name='manage_installation_request'),
    path('installation_history/', views.installation_history, name='installation_history'),
    path('edit-request-date/<int:pk>/', views.edit_request_date, name='edit_request_date'),
    path('update-date/', views.update_date_ajax, name='update_date_ajax'),
    path('delete_request/<int:pk>/', views.delete_installation_request, name='delete_installation_request'),
    path('manage-request-reason/', views.manage_installation_request_with_reason, name='manage_installation_request_with_reason'),
    path('save-installation-amount/', views.save_installation_amount, name='save_installation_amount'),

    path('add_product/', views.add_product, name='add_product'),
    path('product/update-stock/<int:pk>/', views.update_stock, name='update_stock'),
    path('management/product/remove/<int:pk>/', views.remove_product_admin, name='remove_product_admin'),
    path('product/edit-product/<int:pk>/', views.edit_product, name='edit_product'),
    path('marketplace/', views.product_marketplace, name='product_marketplace'),
    path('product/<int:pk>/', views.product_detail, name='product_detail'),
    path('cart/', views.view_cart, name='view_cart'),
    path('cart/add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('cart/remove/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('cart/increase/<int:item_id>/', views.increase_quantity, name='increase_quantity'),
    path('cart/decrease/<int:item_id>/', views.decrease_quantity, name='decrease_quantity'),
    path('cart/address/', views.add_address, name='add_address'),
    path('checkout/', views.checkout, name='checkout'),
    path('payment/', views.payment_page, name='payment_page'),
    path('process-payment/', views.process_payment, name='process_payment'),
    path('payment-success/', views.payment_success, name='payment_success'),
    path('product-orders/', views.product_orders, name='product_orders'),
    path('product-transactions/<int:product_id>/', views.product_transactions, name='product_transactions'),
    
    path('pay-installation/<int:pk>/', views.pay_installation, name='pay_installation'),
    path('installation-order-success/<int:payment_id>/', views.installation_order_success, name='installation_order_success'),
    path('confirm-installation-payment/<int:payment_id>/', views.confirm_installation_payment, name='confirm_installation_payment'),
    path('installation-payment-success/<int:payment_id>/', views.installation_payment_success, name='installation_payment_success'),
    path('installation/receipt/<int:payment_id>/', views.render_installation_receipt, name='view_installation_receipt'),
]